#!/usr/bin/env python3
"""Refresh the bundled reskin seed dict.

Queries Scryfall for every printing with a distinct flavor name, applies
the same DFC front-face reduction the source modules use, and writes the
result to `cod_sync/_seed_data.py`. Commit the generated file before
shipping a release.

Usage:
    python scripts/refresh_seed.py

The runtime in `cod_sync/alt_name.py` does not call Scryfall — this is
the only path that hits the API. Reskins released between cod-sync
releases are not covered until this is re-run.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

import requests

# Make `cod_sync` importable when running from a checkout.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from cod_sync.dfc import front_face  # noqa: E402

_SEARCH = "https://api.scryfall.com/cards/search"
_USER_AGENT = "cod-sync/seed-refresh (+https://github.com/k8rthik/cod-sync)"
_QUERY = "has:flavor_name"
_PAGE_SLEEP = 0.1  # Scryfall asks for 50-100ms between requests.


def main() -> int:
    print("Fetching reskin printings from Scryfall...", file=sys.stderr)
    mapping = _fetch_all_reskins()
    print(f"Resolved {len(mapping)} flavor -> canonical pairs.", file=sys.stderr)
    target = Path(__file__).resolve().parent.parent / "cod_sync" / "_seed_data.py"
    target.write_text(_format_module(mapping), encoding="utf-8")
    print(f"Wrote {target}", file=sys.stderr)
    return 0


def _fetch_all_reskins() -> dict[str, str]:
    """Walk every Scryfall page of `has:flavor_name` and dedupe."""
    mapping: dict[str, str] = {}
    skipped_conflicts: set[str] = set()
    url: str | None = _SEARCH
    params: dict[str, str] | None = {"q": _QUERY, "unique": "prints"}
    page_count = 0

    while url:
        resp = requests.get(
            url,
            params=params,
            headers={"User-Agent": _USER_AGENT, "Accept": "application/json"},
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        page_count += 1

        for card in data.get("data") or []:
            canonical_raw = card.get("name")
            flavor_raw = card.get("flavor_name")
            if not isinstance(canonical_raw, str) or not isinstance(flavor_raw, str):
                continue

            flavor = front_face(flavor_raw)
            canonical = front_face(canonical_raw)
            if not flavor or not canonical or flavor == canonical:
                continue

            existing = mapping.get(flavor)
            if existing is None:
                mapping[flavor] = canonical
            elif existing != canonical:
                # Same flavor name across two different canonical cards.
                # Drop it so runtime falls through to identity rather than
                # silently picking one canonical at random.
                skipped_conflicts.add(flavor)

        if not data.get("has_more"):
            break
        url = data.get("next_page")
        params = None  # next_page URL already embeds the query.
        time.sleep(_PAGE_SLEEP)

    for flavor in skipped_conflicts:
        mapping.pop(flavor, None)
    if skipped_conflicts:
        print(
            f"Skipped {len(skipped_conflicts)} ambiguous flavor name(s): "
            f"{', '.join(sorted(skipped_conflicts))}",
            file=sys.stderr,
        )
    print(f"Walked {page_count} page(s).", file=sys.stderr)
    return mapping


def _format_module(mapping: dict[str, str]) -> str:
    lines = [
        '"""Bundled reskin -> canonical name map.',
        "",
        "Generated by scripts/refresh_seed.py. Do not hand-edit.",
        "Re-run that script and commit the result to add new reskins.",
        '"""',
        "from __future__ import annotations",
        "",
        "SEED: dict[str, str] = {",
    ]
    for flavor in sorted(mapping, key=str.casefold):
        canonical = mapping[flavor]
        lines.append(f"    {flavor!r}: {canonical!r},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    sys.exit(main())
